In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
from konlpy.tag import Hannanum, Komoran, Kkma, Twitter
from sklearn.cluster import AgglomerativeClustering, KMeans, DBSCAN
import scipy.cluster.hierarchy as shc
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [5]:
han = Hannanum()

In [6]:
data = pd.read_excel('data_files/clustering_data.xlsx')
data

검색어  \
0                                    유한양행   
1                                    유한양행   
2                                    유한양행   
3                                    유한양행   
4                                    유한양행   
5                                      라돈   
6                                      라돈   
7                                      라돈   
8                                      라돈   
9                                      라돈   
10                               복면가왕 왕밤빵   
11                               복면가왕 왕밤빵   
12                               복면가왕 왕밤빵   
13                               복면가왕 왕밤빵   
14  복면가왕 왕밤빵15:15B1213:1614:1613:16B11:16   

                                                 기사내용  
0   유한양행은 얀센 바이오테크(Janssen Biotech Inc)와 EGFR표적 항암...  
1   유한양행이 1조4000억원 규모의 기술이전 계약 체결 소식에 가격제한폭까지 치솟았다...  
2   유한양행이 다국적 제약사 얀센에 기술수출했다는 소식에 주가가 5일 장 초반 상한가를...  
3   유한양행은 얀센 바이오테크((Janssen Biotech, Inc.)와 EGFR(상...  
4   유한양행이 1조4000억원 규모 기술 수출 소식에 가격제한폭까지 치솟았다. 유한양행...  
5   최근 침대 매트리스에 이어 온수매트에서도 라돈이 검출됐다는 소식이 알려지면서, 가정...  
6    침대, 생리대, 마스크 등에서 라돈이 검출되면서, 발암 물질 ‘라돈’에 대한 관심...  
7   하이젠 온수매트가 '라돈 온수매트'로 언급되고 있다.\n최근 한 온라인커뮤니티에서는...  
8   겨울 난방 제품인 온수매트에서 라돈이 검출된 가운데 해당 업체가 별 문제가 되지 않...  
9   매트리스, 생리대에 이어 온수 매트에서도 라돈이 검출돼 이슈로 떠올랐다.\n5일 오...  
10  복면가왕’ 88대 가왕 자리는 2연승의 왕밤빵이 차지했다.\n4일 오후 방송된 MB...  
11  복면가왕'에 출연해 왕밤빵에 패하면서 얼굴을 공개한 '축음기' 천단비에 관심이 쏠리...  
12  지난 4일 방송된 MBC ‘복면가왕’에서는 왕밤빵에 맞서 축음기, 조커, 북극곰 버...  
13  복면가왕' 왕밤빵의 정체가 더욱더 오리무중에 빠졌다. \n4일 방송된 MBC 예능프...  
14  복면가왕' 왕밤빵이 첫 방어전에 성공하며 2연승을 차지했다.\n지난 4일 방송된 M...

In [7]:
data.iloc[8,1]

'겨울 난방 제품인 온수매트에서 라돈이 검출된 가운데 해당 업체가 별 문제가 되지 않는다고 말했다.\n5일 방송된 MBC \'생방송 오늘 아침\'에 따르면 일부 온수매트에서 라돈이 검출됐다.\n이날 방송에서 한 주부는 집에서 사용하던 온수매트에서 라돈이 검출돼 비닐로 몇 겹 포장해 창고에 보관해 놓고 있다고 말했다. \n이 주부는 "세살 된 아이와 함께 라돈이 나오는 온수 매트에서 생활했다"며 불안감을 감추지 못했다.\n해당 온수매트에서 나온 라돈 수치는 218베크렐(Bq/㎥)로 기준치를 훌쩍 넘어서는 수치였다.\n음이온 기능을 강조했던 이 매트는 오히려 음이온 때문에 라돈이 검출된 것으로 보인다. \'공포의 대상\'이 된 온수매트를 사용한 소비자들은 한결 같이 사용 후 기침과 콧물이 많이 나왔다고 설명했다.한 주부는 아이와 함께 사용했던 온수매트를 공식 기관에 의뢰해 라돈 수치를 쟀더니 기준치의 10배가 넘는 1,520베크렐이 검출됐다며 불안해 했다.\n그러나 해당 온수매트 제조사는 이에 대해 "한 달 동안 측정을 했는데 수치상으로 정상으로 나와서 별 문제가 되지 않는다"고 말했다. \n한편 방송이 나간 뒤, 온수매트 라돈 피해자 모임 카페에는 해당 제품에 대한 사용 후기 등 라돈 피해를 본 거 같다는 내용의 글이 올라오고 있다.'

In [8]:
# 유사한 텍스트끼리 묶는다..

In [11]:
kor = Komoran()

docs = []

for news in data['기사내용']:
    docs.append(kor.nouns(news))

In [12]:
docs

[['유한양행',
  '얀센',
  '바이오',
  '테크',
  '표적',
  '항암',
  '치료제',
  '기술이전',
  '계약',
  '체결',
  '일',
  '공시',
  '기술',
  '수출',
  '금액',
  '달러',
  '한화',
  '원',
  '계약금',
  '달러',
  '개발',
  '허가',
  '매출',
  '단계',
  '마일스톤',
  '달러',
  '수령',
  '예정',
  '순',
  '매출액',
  '책정',
  '유한양행',
  '관계자',
  '기술이전',
  '계약',
  '수익',
  '인식',
  '임상시험',
  '허가',
  '등',
  '성공',
  '여부',
  '수',
  '미',
  '실현',
  '있다'],
 ['유한양행',
  '원',
  '규모',
  '기술이전',
  '계약',
  '체결',
  '소식',
  '가격제한폭',
  '일',
  '오전',
  '시',
  '3분',
  '유한양행',
  '전날',
  '원',
  '원',
  '거래',
  '사흘',
  '연속',
  '강세',
  '유한양행',
  '글로벌',
  '약사',
  '존슨',
  '앤',
  '존슨',
  'J&J',
  '자회사',
  '얀센',
  '바이오',
  '테크',
  '해제',
  '기술',
  '수출',
  '계약',
  '체결',
  '이날',
  '계약',
  '규모',
  '원',
  '달러',
  '반환',
  '의무',
  '계약금',
  '원',
  '달러',
  '이번',
  '계약',
  '얀센',
  '전',
  '세계',
  '개발',
  '제조',
  '상업',
  '독점',
  '권리',
  '국내',
  '개발',
  '상업',
  '권리',
  '유한양행',
  '유지',
  '유한양행',
  '얀센',
  '바',
  '이',
  '오텍',
  '내년',
  '단일',
  '요법',
  '병용',
  '요법',
  '글로벌',
  '임상시험',
  '공동',
  '진행',


In [14]:
# 숫자로 전환..

# 1.
# countervectorizing

#         형태소1, 형태소2, 형태소3, 형태소4 ...
# 문서 1     0        2        1        0         =>(0,2,1,0, ...)
# 문서 2     1        1        0        0         =>(1,1,0,0, ...)         
# 문서 3     0        0        3        0         =>(0,0,3,0, ...)    
# ...

# 2.
# tfidf vectorizing
# 문서에서 형태소1의 등장수 : tf
# 전체 문서에서 형태소1이 등장한 문서수 : idf 
# tfidf = tf/idf

#         형태소1, 형태소2, 형태소3, 형태소4 ...
# 문서 1     0       0.3      0.01      0         =>(0, 0.3, 0.01, 0, ...)
# 문서 2   0.003    0.01       0        0         =>(0.003, 0.01, 0, 0, ...)         
# 문서 3     0        0       0.35        0         =>(0, 0, 0.35, 0, ...)    
# ...

SyntaxError: invalid syntax (Temp/ipykernel_3536/2584788070.py, line 7)

In [21]:
L = ['나라', '대한', '민국']
' '.join(L)

'나라 대한 민국'

In [22]:
# CountVectorizer에 값을 넣기위해 문장의 형식으로 변경
for i in range(len(docs)):
    docs[i] = ' '.join(docs[i])

In [25]:
docs

['유한양행 얀센 바이오 테크 표적 항암 치료제 기술이전 계약 체결 일 공시 기술 수출 금액 달러 한화 원 계약금 달러 개발 허가 매출 단계 마일스톤 달러 수령 예정 순 매출액 책정 유한양행 관계자 기술이전 계약 수익 인식 임상시험 허가 등 성공 여부 수 미 실현 있다',
 '유한양행 원 규모 기술이전 계약 체결 소식 가격제한폭 일 오전 시 3분 유한양행 전날 원 원 거래 사흘 연속 강세 유한양행 글로벌 약사 존슨 앤 존슨 J&J 자회사 얀센 바이오 테크 해제 기술 수출 계약 체결 이날 계약 규모 원 달러 반환 의무 계약금 원 달러 이번 계약 얀센 전 세계 개발 제조 상업 독점 권리 국내 개발 상업 권리 유한양행 유지 유한양행 얀센 바 이 오텍 내년 단일 요법 병용 요법 글로벌 임상시험 공동 진행 예정 유한양행 개발 허가 상업 성공 단계 마일스톤 달러 원 수 임상시험 허가 상업 실패 경우 기술이전 계약 종료 경우 유한양행 얀센 측 지급 위약금',
 '유한양행 다국적 약사 얀센 기술 수출 소식 주가 일 장 초반 상한가 유한양행 이날 오전 시 분 유가증권 시장 거래 일 원 원 거래 유한양행 얀센 바이오 테크 상피 세포 성장 인자 수용체 표적 항암 치료제 기술 이전 계약 체결 이날 장 개장 공시 이번 계약금 달러 개발 상업 단계 달러 기술 수출 규모 달러 원 삼성증권 연구원 유한양행 이번 기술 수출 계약 소식 한미약품 이후 기술 이전 계약 투자자 갈증 해소 전망 한미약품 사노피 기술 이전 계약 체결 이후 번 계약 규모 이다 말',
 '유한양행 얀센 바이오 테크 상피 세포 성장 인자 수용체 표적 항암 치료제 기술이전 계약 일 공시 기술 수출 금액 미화 달러 계약금 달러 개발 허가 매출 단계 마일스톤 달러 수령 예정 계약 지역 한국 제외 세계',
 '유한양행 원 규모 기술 수출 소식 가격제한폭 유한양행 우도 상한 일 오전 시 분 유한양행 일 대비 원 급등 원 기록 중 유한양행 우 원 원 거래 이날 유한양행 다국적 제약 사인 얀센 비소 세포 폐암 치료제 글로벌 판권 한국

In [27]:
vec = CountVectorizer()
x = vec.fit_transform(docs)
x

<15x485 sparse matrix of type '<class 'numpy.int64'>'
	with 815 stored elements in Compressed Sparse Row format>

In [30]:
news_arr = x.toarray()
news_arr

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
news_arr.shape

(15, 485)

In [34]:
news_arr[0] # aparse matrix => 학습이 잘 안됨.. 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [36]:
vec.get_feature_names()

C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['10분',
 '20대',
 '3년',
 '3분',
 '8월',
 'k7',
 '가격제한폭',
 '가동',
 '가면',
 '가수',
 '가스',
 '가요',
 '가운데',
 '가정',
 '가창력',
 '각각',
 '각시탈',
 '각자',
 '각종',
 '갈증',
 '감미',
 '감사',
 '감성',
 '감회',
 '강세',
 '강조',
 '개발',
 '개장',
 '거래',
 '거론',
 '거짓말',
 '건빵선생과',
 '검사',
 '검출',
 '게시물',
 '게재',
 '겨울',
 '결과',
 '결정',
 '결함',
 '경구',
 '경연',
 '경우',
 '계약',
 '계약금',
 '계획',
 '고객',
 '골자',
 '곳곳',
 '공간',
 '공개',
 '공기',
 '공동',
 '공시',
 '공식',
 '공지',
 '공포',
 '관객',
 '관계자',
 '관련',
 '관심',
 '괴담',
 '교환',
 '구매',
 '구입',
 '구청',
 '국내',
 '국제',
 '군청',
 '궁금증',
 '권고',
 '권리',
 '규모',
 '극찬',
 '글로벌',
 '글쓴이',
 '금액',
 '급등',
 '기관',
 '기구',
 '기능',
 '기록',
 '기본',
 '기분',
 '기술',
 '기술이전',
 '기자',
 '기준',
 '기체',
 '기침',
 '김성주',
 '김용진',
 '김현철',
 '나무',
 '난방',
 '내년',
 '내용',
 '네이버',
 '노래',
 '논란',
 '누리꾼',
 '눈길',
 '눈물샘',
 '능력',
 '다국적',
 '다음',
 '단계',
 '단위',
 '단일',
 '달러',
 '당시',
 '대결',
 '대구',
 '대구시',
 '대비',
 '대상',
 '대여',
 '대여료',
 '대응',
 '대인',
 '데뷔',
 '도전',
 '도전자',
 '독점',
 '동안',
 '된다',
 '드라마',
 '때문',
 '라돈',
 '라운드',
 '러브송',
 '레인',
 '로만',
 '마스크',
 '마음',
 '마일스톤',
 '마지막',
 '매력

In [38]:
news_df = pd.DataFrame(news_arr, columns=vec.get_feature_names())
news_df.head()

C:\Users\bitcamp\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


10분  20대  3년  3분  8월  k7  가격제한폭  가동  가면  가수  ...  확대  확인  확충  환경  환경부  활동  \
0    0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
1    0    0   0   1   0   0      1   0   0   0  ...   0   0   0   0    0   0   
2    0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
3    0    0   0   0   0   0      0   0   0   0  ...   0   0   0   0    0   0   
4    0    0   0   0   0   0      1   0   0   0  ...   0   0   0   0    0   0   

   효소  후기  후보  흡연  
0   0   0   0   0  
1   0   0   0   0  
2   0   0   0   0  
3   0   0   0   0  
4   1   0   1   0  

[5 rows x 485 columns]

In [40]:
from sklearn.cluster import KMeans

In [41]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(news_df)

KMeans(n_clusters=3)

In [42]:
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0])

In [45]:
cluster = AgglomerativeClustering(n_clusters=3, linkage='ward')
cluster.fit_predict(news_df)

array([0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 0, 0], dtype=int64)

In [48]:
cluster = DBSCAN(eps=3, min_samples=5)
cluster.fit_predict(news_df)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
      dtype=int64)

In [49]:
# 차원 축소

In [50]:
from sklearn.decomposition import PCA

In [54]:
pca = PCA(n_components=2)
arr_pca = pca.fit_transform(news_df)

In [55]:
kmeans = KMeans(n_clusters=3)
kmeans.fit_predict(arr_pca)

array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 1, 1])

In [71]:
vec = TfidfVectorizer(max_df=0.8, min_df=0.2)
x = vec.fit_transform(docs)
news_arr = x.toarray()
news_arr.shape

(15, 84)

In [73]:
kmeans = KMeans(n_clusters=3)
kmeans.fit(news_arr)

KMeans(n_clusters=3)

In [75]:
kmeans.predict(news_arr)

array([2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [77]:
cluster = AgglomerativeClustering(n_clusters=3, linkage='ward')
cluster.fit_predict(news_arr)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2], dtype=int64)

In [79]:
cluster = DBSCAN(eps=3, min_samples=5)
cluster.fit_predict(news_arr)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)